pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('create docker images') {
            steps {
                echo "=============== start build image ==============="
                dir ('/home/ubuntu/jenkins/workspace/build-2/') {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}